version: "3"

services:
  meilisearch:
    image: ghcr.io/kunalsin9h/meilisearch:latest
    ports:
      - "7700:7700"
    restart: always
    deploy:
      mode: global
    volumes:
      - ./meilisearch/data.ms:/meilisearch/data.ms
    environment:
      MEILI_MASTER_KEY: "--make-a-key--"
      MEILI_IGNORE_DUMP_IF_DB_EXISTS: true
      MEILI_IGNORE_MISSING_DUMP: true

